### ISSUE TITLE
Implementation of Put and Delete for Model

### ISSUE THREAD

**Issue by cgarciae** [dart-lang/gcloud#14]
I am reading the Python API and thought that `put` is a very convenient function, so I created my own implementation of a `Put` and `Delete` methods, which I wanted to share.

```
abstract class SuperModel extends Model
{

    Future<dynamic> Put ()
    {
        return db.commit(inserts: [this]);
    }
    Future<dynamic> PutF (dynamic o) => Put ();


    Future<dynamic> Delete ()
    {
      return db.commit(deletes: [key]);
    }
    Future<dynamic> DeleteF (dynamic o) => Delete ();
}
```

The methods ending in `F` are so you can easily pass them as functions to `then` like this

```
future.then (model.PutF);
```

Reads nicer and codes quicker.

**Comment by sigurdm** [comment]
Closing as obsolete. Please open new issue if this is still relevant.
