### ISSUE TITLE
Add .ancestor (Key ancestorKey) method to Query class

### ISSUE THREAD

**Issue by cgarciae** [dart-lang/gcloud#15]
Create a `Query.ancestor (Key ancestorKey)`  method. I feel this code

```
db.query (Item)
    ..ancestor (itemsRoot)
    ..order ('name');
```

is more readable than the one proposed in the tutorial:

```
query = db.query (Item, ancestorKey: itemsRoot)
        ..order ('name');
```

and you could compose better through functions that take and return a `Query` object. This example uses a functional style

```
Function orderBy(String field) => (Query query) => query..order (field);
Function withAncestor (Key ancestorKey) => (Query query) => query..ancestor (ancestorKey);

Function compose (Function f, Function g) => (x) => f (g (x));

//Later on
Query myQuery = compose (orderBy ('name'), withAncestor (itemsRoot)) (query);
```

The average user might not do this, but it is important to have composability when creating an API. Also, as a new user to GAE, it took me a while to know what the ancestor key did, mostly because it looks like a parameter of the query more than a filtering/boosting mechanism as shown by the Python API.

**Comment by sigurdm** [comment]
Closing as obsolete. Please open new issue if this is still relevant.
