### ISSUE TITLE
Support googleapis v12.0.0

### ISSUE THREAD

**Issue by davidmigloz** [dart-lang/gcloud#178]
The current constraints prevent from using the latest version of `googleapis` (v12.0.0)

https://github.com/dart-lang/gcloud/blob/69bb2a99bcde12f85307fd8873f2e95e97076859/pubspec.yaml#L16

```
Because gcloud 0.8.11 depends on googleapis >=3.0.0 <12.0.0 and no versions of gcloud match >0.8.11 <0.9.0, gcloud ^0.8.11 requires googleapis >=3.0.0 <12.0.0.
So, because x depends on both gcloud ^0.8.11 and googleapis ^12.0.0, version solving failed.
```

**Comment by jonasfj** [comment]
For the record, pull requests are also welcome. Things like this is usually just bumping the version constraint :rofl: 

A new version of `package:gcloud` should be available now --> https://pub.dev/packages/gcloud

**Comment by davidmigloz** [comment]
That was quick, thanks!

I didn't send a PR because I saw in the release notes of v0.8.12:
> Support the latest version 12.0.0 of the googleapis package.

So I though, maybe there was some regression after updating the constraints and the update was reverted. 

(otherwise I would have sent it 🙂)
