### ISSUE TITLE
[datastore] Handle PartitionId [Namespace,DatasetId] correctly throughout all implementations

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/gcloud#2]
There are a few things we need to consider:
- serializing/deserializing datastore.Key's (canonicalize to something)
- comparing datastore.Key's correctly (taking the default partition, default namespace into account)
- "String datasetId" to datastore.Partition

**Comment by sigurdm** [comment]
Closing as obsolete. Please open new issue if this is still relevant.
