### ISSUE TITLE
[datastore] Consider removing the optional partition parameter in `DatastoreDB.query`.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/gcloud#26]
The optional `partition` parameter to `DatastoreDB.query` is redundant in cases where an `ancestorKey` is given or when it is `null`.

For queries with a `partition` but without an `ancestorKey`, we could force `ancestorKey` to be `partition.emptyKey`. Doing so would enable us to get rid of `partition` entirely.

**Comment by sigurdm** [comment]
Closing as obsolete. Please open a new issue if this is still relevant.
