### ISSUE TITLE
please widen dependencies on googleapis + googleapis_beta

### ISSUE THREAD

**Issue by zoechi** [dart-lang/gcloud#28]
```yaml
  googleapis: '>=0.2.0 <0.11.0'
  googleapis_beta: '>=0.3.0 <0.15.0'
```

**Comment by sethladd** [comment]
Can you please send over a pull request?

**Comment by mkustermann** [comment]
Thanks for the hint.

It requires us to publish anyway, so I went ahead and widened the constraints.

**Comment by zoechi** [comment]
@sethladd I tried, but run into obstacles when running the tests and went with the issue instead.

**Comment by sethladd** [comment]
Thanks for giving it a shot!
