### ISSUE TITLE
[cloudstorage] bucket.list is very slow for large buckets, paging is much faster - utils library?

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/gcloud#36]
I have a bucket with ~50k items in it. Calling bucket.list to get the names takes around 15 minutes to complete.

Replacing the code with something like the following approximate code:

```
const PAGE_SIZE = 1000;

  Set<String> names = new Set<String>();
  storage.Page page = await bucket.page(pageSize: PAGE_SIZE);

  while (!page.isLast) {
    names.addAll(page.items.map((x) => x.name));
    page = await page.next(pageSize: PAGE_SIZE);
  }
  names.addAll(page.items.map((x) => x.name));

  return names;
```

Cuts the execution time by over 10x, but does make more calls.

I'm starting to gather a number of support functions like this - what is the best thing to do with them? Build an unofficial utilities package? Send a PR to change the implementation/add to the existing Dart wrapper? What would be the most help?

**Comment by sigurdm** [comment]
Now we have a `Bucket.page()` that goes through the files by paging!
