### ISSUE TITLE
[datastore] Support value transformations for 'db.filter

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/gcloud#37]
There is already a [todo in the code](https://github.com/dart-lang/gcloud/blob/d6538f1a39a8362dfb5263417e9ad5547512fb14/lib/src/db/db.dart#L165) for this.

An example is being able to do

```dart
var parentKey = db.emptyKey.append(Person, id: 10);
var query = db.query(Person)..filter('parent =', parentKey);
var result = (await query.run()).toList();
```

Currently the `parentKey` is not transformed to a `datastore.Key` object.

**Comment by sgjesse** [comment]
From: http://stackoverflow.com/questions/33873697/filter-by-keyproperty-in-google-datastore-with-dart
