### ISSUE TITLE
[datastore] Should update package to use Cloud Datastore v1 API before the Beta 2 decommission date.

### ISSUE THREAD

**Issue by avoivo** [dart-lang/gcloud#41]
I got an email with the following content.

**_Google Cloud Datastore is turning down the v1beta1 and v1beta2 API on September 30, 2016. After the decommission date, you will no longer be able to access either version of the API and your requests will fail with an error.**_

Is it on your plans to change it?

**Comment by mkustermann** [comment]
We've just updated `package:googleapis` and `package:googleapis_beta` in https://github.com/dart-lang/googleapis/commit/488dbe75bc81cb03059a661a89fb4e312dfaca90  and published them.

The update included the new `package:googleapis/datastore/v1.dart` library.

We will change `package:gcloud` to use this new library.

**Comment by mkustermann** [comment]
CL is up for review: https://codereview.chromium.org/2285803002/
