### ISSUE TITLE
Add functionality to retrieve resumable upload URL

### ISSUE THREAD

**Issue by enyo** [dart-lang/gcloud#42]
Right now, the only way to [get a resumable upload URL](https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload) is to do the HTTP request "manually".

The problem with that, is that the storage does not expose the `authClient` which must be used to do the authenticated request to the storage.

So in our app, we first choose which client to use (whether we are in local development or in flex env), then create the authClient with either `auth.clientViaServiceAccount` or `auth.clientViaMetadataServer` and then do the request.

This seems very redundant, since all of this logic is already present in the `gcloud/storage` implementation, but isn't exposed (all of that functionality is private).

Adding a `getResumableUploadUrl` to `Storage` would be the easiest solution (and would benefit everybody who wanted to get such a Url), but if that is not wanted, it would be enough to expose the `authClient` (adding a `auth.AuthClient get authClient => _authClient;`) in the `Storage` class.

If you would be willing to accept such a change, I could propose a PR.

**Comment by mkustermann** [comment]
At least for `package:appengine` applications the auth client used for the storage api should be [injected](https://github.com/dart-lang/appengine/blob/3b6121c8958194f3f0692a2e98c7692b286a58a8/lib/src/appengine_internal.dart#L317) into the service scope (afaik) - it uses an oauth2 token with oauth2 scopes necessary for the storage API.

So you should be able to just use it via `authClientService` (from `package:gcloud/http.dart`).

Does this work?

**Comment by enyo** [comment]
Thank you! Will try and get back to you.

**Comment by sigurdm** [comment]
Closing as obsolete. Please open a new issue if this is still relevant.
