### ISSUE TITLE
allow to connect to the datastore emulator

### ISSUE THREAD

**Issue by zoechi** [dart-lang/gcloud#48]
I haven't found a way to connect to a gcloud sdk datastore emulator

**Comment by mkustermann** [comment]
It is possible to use the datastore interface in `package:gcloud` with the datastore emulator via the gRPC-based datastore implementation available in `package:appengine`.

See [appengine/README.md#using-the-datastore-emulator](https://github.com/dart-lang/appengine/blob/master/README.md#using-the-datastore-emulator).

When the in-development [package:grpc](https://pub.dartlang.org/packages/grpc) is ready, we could move the implementation out of package:appengine into package:gcloud (currently the appengine package contains a minimal working grpc implementation).

**Comment by zoechi** [comment]
Sounds fine. I already found how to do it in `appengine` and it seems to work.
Thanks a lot.
Feel free to close this issue if you don't want to keep it for the mentioned task.
