### ISSUE TITLE
Add generics support

### ISSUE THREAD

**Issue by enyo** [dart-lang/gcloud#54]
With dart 2.0 this package is a bit inconvenient to use, because queries always return a generic `Stream<Model>` instead of the requested model. This results in lots of code like this:

```dart
final query = db.query(models.Page)
  ..filter('isPublished =', true);
return query.run().cast<models.Page>();
````

Ideally `gcloud` would support generics like this:

```dart
final query db.query<models.Page>()
  ..filter('isPublished =', true);
return query.run(); // <-- Stream<models.Page>
```

**Comment by enyo** [comment]
I was also thinking of adding generics to the `Model` class so the type of the id can be fixed.

```dart
class Model<T> {
  T id;
}
```

Because we exclusively use `String`s as IDs, and we would need to use `myModel.id.toString()` everywhere used, since we can't override the `id` property with a more narrow type.

**Comment by enyo** [comment]
@kevmoo @mkustermann tell me what you think about the idea of adding generics to `id` and I can add it to the MR. (And obviously it would be great if you could look at the MR as well)

**Comment by mkustermann** [comment]
@enyo This makes the API much nicer to use, so it's great :) 

The `Model.id` can be an int or a String atm iirc, so I'm not sure if this is feasible. Also the keys have `parentKey`s, which are untyped. Maybe we need to think about this a bit more.

**Comment by enyo** [comment]
@mkustermann yeah I ran into the problem with parents keys  while adding the generics support to keys. The rest is working well.

The fact that the keys need to be int or String is unfortunately something that can’t be represented in generics so the user of the library needs to provide one of the two when extending `Model`. I think that’s acceptable.

In regards to the parent keys I thought about providing a second generic type to Model and Key that defines the parent of type, but that seems a bit convoluted and only solves one hierarchy. I’m not sure there is a proper solution for that.
