### ISSUE TITLE
[datastore] Refactoring / Extending low level Datastore API

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/gcloud#6]
This is a metabug which all Refactoring/Extending TODOs in the low level Datastore API can refer to.

Currently the following changes should be done:
- Partition: Add "dataset-id"
- OrderDirection: Make it private and move static Ascending/Descending members to 'class Order'
- Order: Make direction optional and defaulting to Ascending
- Datastore.commit: Split insert into: insert/update/upsert
- Datastore.query: Make this return a Stream / Pageable

**Comment by sigurdm** [comment]
Closing as obsolete. Please open new issue if this is still relevant.
