### ISSUE TITLE
Not working with built_value library (dev channel)

### ISSUE THREAD

**Issue by eusaro** [dart-lang/gcloud#92]
When I execute this command ``` flutter pub run build_runner watch``` I get the following error
```Could not find a file named "pubspec.yaml" in "/home/cinderella/development/flutter/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.3" ```

If I remove the gcloud dependency, then it works.

I'm using it in Dart linux, not Flutter.

Update -
It seems to work well on stable channel

<details><summary>Flutter doctor</summary>
<p>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.16.1, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.43.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

</p>
</details>

**Comment by sigurdm** [comment]
Thanks for reporting.
I was not able to reproduce.
Could you post your `pubspec.yaml`, and some info about the build setup?

**Comment by eusaro** [comment]
I just came back to dev channel and this time worked well. I don't know what could have been. I cleaned all files when switching between channels. Sorry for that.
